### ISSUE TITLE
민수 오랜만이네 잘 지내나 ㅋㅋㅋ

### ISSUE THREAD

**Issue by kyupkyup** [Jackson-Kang/Jackson-Kang#1]

**Comment by Jackson-Kang** [comment]
ㅋㅋㅋㅋㅋ 형님 이거 언제 남기셨어요..
이제봤네요 ㅋㅋㅋㅋ 잘지냅니다 햄 ㅋㅋㅋㅋ

햄 어디계세요? 한번 뵈어야죠 ㅋㅋㅋ

**Comment by kyupkyup** [comment]
나 지금 재택중...ㅋㅋㅋㅋ 판교 다니니까 나중에 출근하면 함 보자 ㅋㅋㅋㅋ

**Comment by Jackson-Kang** [comment]
ㅋㅋㅋ 좋습니다 형님!
편하실때 한번 뵈어요 ㅎㅎ
